[[layers]]
  name = "lang#java"

[[layers]]
  name = "lsp"
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
      "java",
      "-Declipse.application=org.eclipse.jdt.ls.core.id1",
      "-Dosgi.bundles.defaultStartLevel=4",
      "-Declipse.product=org.eclipse.jdt.ls.core.product",
      "-Dlog.protocol=true",
      "-Dlog.level=NONE",
      "-noverify",
      "-Xmx1G",
      "-jar",
      "/home/xuechun/jdt/plugins/org.eclipse.equinox.launcher_1.6.500.v20230717-2134.jar",
      "-configuration",
      "/home/xuechun/jdt/config_linux",
      "-data",
      "/home/xuechun/.cache/javalsp"
    ]


